---
title: "Distribucion Geometrica"
author: "Diego Delgado Palomares"
date: "7/10/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytext.verbosse = T)
library(reticulate)
reticulate::use_python("c:/ProgramData/Anaconda3/python.exe")
```

# Distribución Geométrica $X\sim \text{Ge}(p)$

##### Su función de densidad viene dada por
$$\begin{matrix}
f(k)=(1-p)^{k}p & \text{si empieza en 0}
\\
f(k)=(1-p)^{k-1} & \text{si empieza en 1}
\end{matrix}$$

##### Su función de ditribución es 

$$F(x)=\left\{\begin{matrix}
0 & \text{si } x<0\\
1-(1-p)^{k+1} & \text{si } k\le x <k+1 , k \in \mathbb{N}
\end{matrix}
\right.$$

#### con Esperanza $E(X) = \frac{1-p}{p}$

#### y Varianza $Var(X)=\frac{1-p}{p^2}$ 

## Propiedad de la falta de memoria
###### Si $X$ es una variable aleatoria $\text{Ge}(p)$ , entonces: 
$$p\{ X\ge m + n : X\ge n \}= p \{ X\ge m \} ~\forall ~m, n = ~0,1,..$$

Sea $X=Geom(p=0.1)$ la distribución que modela la probabilidad de intentar abrir una puerta hasta conseguirlo


```{r}
library(Rlab)
p=0.1
plot(dgeom(0:100,p))
plot(0:1000, pgeom(0:1000, p), ylim = c(0,1)  )
qgeom(0.5,p)
qgeom(0.7,p)
hist(rgeom(10000,p))

```

```{python}
from scipy.stats import geom
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1,1)
p=0.3
mean, var, skew, kurt = geom.stats(p, moments = "mvsk")
print("Media %f"%mean)
print("Varianza %f"%var)
print("Sesgo %f"%skew)
print("Curtosis %f"%kurt)

x = np.arange(geom.ppf(0.01,p), geom.ppf(0.99,p))
ax.plot(x,geom.pmf(x,p), "bo", ms = 8, label= "Función de probabilidad geométrica (0.3)")
ax.vlines(x,0, geom.pmf(x,p),  colors="b", lw=4, alpha = 0.5) 

rv = geom(p)
ax.vlines(x,0,rv.pmf(x), colors ="k", linestyles = '--', lw = 1,
label = "Frozen PMF")
ax. legend(loc= "best")
plt.show()

fig, ax = plt.subplots(1,1)
prob = geom.cdf(x,p)
ax.plot(x, prob, "bo", ms = 8, label = "Función de acumulación")
plt.show()

fig, ax = plt.subplots(1,1)
r = geom.rvs(p,size = 10000)
plt.hist(r)
plt.show()
```

